# Sets the title and description of your site
title: Eashwar S.C. Krishna
description: Incoming MD Candidate, rural health researcher and advocate, health sociologist

# This is the line that adds the theme
theme: jekyll-theme-minimal
