# Sets the title and description of your site
title: Eashwar S.C. Krishna
description: Sociology & Molecular Biology @ UConn | Incoming MD Candidate | Rural Health Researcher | Health Sociologist

# This is the line that adds the theme
theme: jekyll-theme-slate
